import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/ui/Nav";
import {config} from "@fortawesome/fontawesome-svg-core"
import "@fortawesome/fontawesome-svg-core"

config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MediByte",
  description: "Generated by MonoErea",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
          <div className="flex-grow overflow-y-auto bg-page text-">{children}</div>
        </div>
      </body>
    </html>
  );
}
